name: Deploy RickAndMorty UI

on:
  push:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "rickandmortyui"
  ConnectionStrings__AzureConnectionString: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      - name: Restore dependencies
        run: dotnet restore ./RickAndMorty.UI/RickAndMorty.UI.csproj

      - name: Build
        run: dotnet build ./RickAndMorty.UI/RickAndMorty.UI.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./RickAndMorty.UI/RickAndMorty.UI.csproj --configuration Release --output ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ./publish
        env:
          AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.UI_PUBLISH_SECRET }}
